name: Publish Github

on:
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'
    branches:
      - master
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
    branches:
      - master

jobs:
  check-packages-github:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      continue: ${{ steps.check.outputs.continue }}
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Check packages where versions were changed
        id: check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ github.workspace }}/.github/workflows/check-versions.sh

  publish-github:
    needs: check-packages-github
    if: ${{ needs.check-packages-github.outputs.continue == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Publish Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

      - name: Publish Pre-Release
        if: ${{ github.event_name == 'pull_request' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          version=$(jq -r '.version' package.json)
          pre_release=$(echo $version | cut -f2 -sd-)

          if [[ ! -z "$pre_release" ]]; then
            npm publish --tag dev
          fi
